version: '3.8'

services:


  db:
    restart: always
    image: postgres:latest
    environment:
     - POSTGRES_PASSWORD=qwerty
    ports: 
    - 5432:5432
    # command: docker exec -i avito-db-1 psql -U postgres -d postgres < ./schema/000001_init.up.sql
  
  cache:
    restart: always
    image: redis:latest
    environment:
      REDIS_PASSWORD: "qwerty"
    ports: 
    - 6379:6379